

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: beauty_book
      MYSQL_USER: user
      MYSQL_PASSWORD: Qwerty1234
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
