FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

# Копируем файлы проекта
COPY . .

# Собираем приложение
RUN mvn clean package -DskipTests -X

FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

ENV JAVA_OPTS="-Xms512m -Xmx1024m"
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"] 