spring:
#  flyway:
#    baseline-on-migrate: true
#    locations: classpath:db/migration
#  datasource:
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
#    name: beauty-book

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  access:
    key: "X30INcpL2Yzf80ArITEdwLegdAFT2dkeq1hxlR7waOk="
  refresh:
    key: "u1vxX56P6a+4tWS2RLt0qIG9yF8DbW6d1pv4JUQI+dk="


logging:
  level:
    org.springframework.security: DEBUG  # Включение отладки для Spring Security
    org.springframework.mail: DEBUG      # Включение отладки для почтовых операций
