spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    admin-email: ${MAIL_ADMIN_EMAIL}

jwt:
  access:
    key: ${JWT_ACCESS_KEY}
  refresh:
    key: ${JWT_REFRESH_KEY}

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration
