spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: beauty-book


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  profiles:
    active: prod

logging:
  level:
    org.springframework.security: DEBUG  # Включение отладки для Spring Security
    org.springframework.mail: DEBUG      # Включение отладки для почтовых операций
