spring:
    datasource:
        url: jdbc:mysql://localhost:3306/beauty_book_local
        username: ${DB_USERNAME_LOCAL}
        password: ${DB_PASSWORD_LOCAL}

    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

