spring:
  servlet:
    multipart:
      max-file-size: 50MB        # Максимальный размер одного файла (50MB)
      max-request-size: 500MB
  profiles:
    active: prod
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: beauty-book

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always


  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: mail.gmx.net
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}


jwt:
  access:
    key: ${ACCESS_KEY}
  refresh:
    key: ${REFRESH_KEY}

logging:
  level:
    org.springframework.security: DEBUG  # Включение отладки для Spring Security
    org.springframework.mail: DEBUG      # Включение отладки для почтовых операций
