spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: Beautybooking@gmx.de  # Ваш адрес электронной почты GMX
    password: USGCY7UA7TQUYHCUQELM  # Ваш пароль для электронной почты GMX
    host: mail.gmx.net  # SMTP-сервер
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    admin-email: Beautybooking@gmx.de  # Адрес вашей электронной почты для администратора

jwt:
  access:
    key: "X30INcpL2Yzf80ArITEdwLegdAFT2dkeq1hxlR7waOk="
  refresh:
    key: "u1vxX56P6a+4tWS2RLt0qIG9yF8DbW6d1pv4JUQI+dk="

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

cloudinary:
  cloud_name: beautyBook
  api_key: 276144613127592
  api_secret: fgM1EQhBV_ewbZ6gR26_sJMoQU0



# Настройки для Flyway
flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration
