spring:
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: beauty-book

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmx.net
    port: 587
    username: Beautybooking@gmx.de
    password: USGCY7UA7TQUYHCUQELM
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000

logging:
  level:
    org.springframework.security: DEBUG  # Включение отладки для Spring Security
    org.springframework.mail: DEBUG      # Включение отладки для почтовых операций
