spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beauty_book
    username: root
    password: Iplari22!
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    username: Beautybooking@gmx.de
    password: Paroljotemaila007!
    host: mail.gmx.net
    port: 587
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
    admin-email: Beautybooking@gmx.de

jwt:
  access:
    key: X30INcpL2Yzf80ArITEdwLegdAFT2dkeq1hxlR7waOk=
  refresh:
    key: u1vxX56P6a+4tWS2RLt0qIG9yF8DbW6d1pv4JUQI+dk=

logging:
  level:
    org:
      springframework:
        security: DEBUG
        mail: DEBUG

cloudinary:
  cloud_name: beautybook
  api_key: 276144613127592
  api_secret: fgM1EQhBV_ewbZ6gR26_sJMoQU0

flyway:
  baseline-on-migrate: true
  locations: classpath:db/migration
