spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  profiles:
    active: local
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      url: ${SPRING_REDIS_URL:redis://localhost:6379}
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: always
  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: ${MAIL_HOST:mail.gmx.net}
    port: ${MAIL_PORT:587}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

jwt:
  access:
    key: ${ACCESS_KEY}
  refresh:
    key: ${REFRESH_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.web: DEBUG
    org.springframework.jdbc: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.end: DEBUG
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
  data:
    redis:
      url: ${SPRING_REDIS_URL}
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  sql:
    init:
      mode: never
  mail:
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    host: ${MAIL_HOST:mail.gmx.net}
    port: ${MAIL_PORT:587}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  access:
    key: ${ACCESS_KEY}
  refresh:
    key: ${REFRESH_KEY}

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    com.example.end: INFO
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.data.redis: DEBUG
