spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    name: beauty-book

  # Настройки JPA и Hibernate
  jpa:
    hibernate:
      ddl-auto: update  # Попробуйте 'create' для чистой инициализации
    show-sql: true       # Для логирования SQL-запросов
    properties:
      hibernate:
        format_sql: true  # Для форматирования SQL-запросов

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    path: /swagger-ui.html
