#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  mail:
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    host: smtp.gmx.net
#    port: 587
#    properties:
#      mail:
#        debug: true
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#jwt:
#  access: ${JWT_ACCESS_KEY}
#
#  refresh: ${JWT_REFRESH_KEY}
#
#
#cloudinary:
#  cloud_name: ${CLOUD_NAME}
#  api_key: ${cloudinary.api_key}
#  api_secret: ${cloudinary.api_secret}
#
